unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix

set -g mode-keys vi
set -g mouse on
set -g default-terminal "tmux-256color"

# Windows
bind-key l next-window
bind-key h previous-window
bind-key b set-option status
bind c new-window -c "#{pane_current_path}"

# dont exit copy mode when mouse drag
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection -x

set -g pane-border-status off
set -g pane-border-format " #{pane_title} "

# Workspace presets
bind C-c display-menu -T "Workspaces" \
  "enjin frontends" e "new-window -n enjin -c ~/repos/enjin/enjin-pelanggan \
    ; set-window-option pane-border-status top \
    ; select-pane -T pelanggan \
    ; split-window -h -c ~/repos/enjin/enjin-konsol \
    ; select-pane -T konsol \
    ; split-window -h -c ~/repos/enjin/enjin-proksi \
    ; select-pane -T proksi \
    ; select-layout even-horizontal \
    ; select-pane -t 0"

# Plugins
set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "#249708"
set -g @minimal-tmux-right false

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'

run '~/.tmux/plugins/tpm/tpm'
